name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true

     # Cache crates.io index and registry
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
          

    # Cache cloned git dependencies
    - name: Cache cargo git
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-git-

    # Cache compilation artifacts
    - name: Cache compiled target
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-
            
    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.1"

    - name: install x11 dev libs
      run: sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
    - name: install some more dev libs
      run: sudo apt-get install libgtk-3-dev pkg-config
    
    - name: Run tests
      run: cargo test --all-targets
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: executable
        path: target/release/game

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true



     # Cache crates.io index and registry
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
          

    # Cache cloned git dependencies
    - name: Cache cargo git
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-git-

    # Cache compilation artifacts
    - name: Cache compiled target
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-

    - name: cmake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.1"
    - name: Run tests
      run: cargo test --all-targets
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: windows executable
        path: target/release/game.exe
